# Generated by Django 4.2.6 on 2023-10-17 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbContractContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2m', models.BigIntegerField(blank=True, db_column='M2M', null=True)),
                ('oy', models.BigIntegerField(blank=True, db_column='OY', null=True)),
                ('ty', models.BigIntegerField(blank=True, db_column='TY', null=True)),
            ],
            options={
                'verbose_name': '계약 종류',
                'verbose_name_plural': '계약 종류',
                'db_table': 'tb_contract_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbContractLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now_add=True, db_column='Change_time', verbose_name='변경 시간')),
                ('contract', models.CharField(blank=True, db_column='Contract', max_length=20, null=True, verbose_name='계약 종류')),
                ('tenure_in_months', models.BigIntegerField(blank=True, db_column='Tenure_in_months', null=True, verbose_name='계약 개월 수')),
                ('monthly_charge', models.FloatField(blank=True, db_column='Monthly_Charge', null=True, verbose_name='기본 요금')),
                ('total_revenue', models.FloatField(blank=True, db_column='Total_Revenue', null=True, verbose_name='총 요금')),
            ],
            options={
                'verbose_name': '요금제 수정 로그',
                'verbose_name_plural': '요금제 수정 로그',
                'db_table': 'tb_contract_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbContractMonthc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_20', models.BigIntegerField(blank=True, db_column='MC_20', null=True)),
                ('mc_30', models.BigIntegerField(blank=True, db_column='MC_30', null=True)),
                ('mc_40', models.BigIntegerField(blank=True, db_column='MC_40', null=True)),
                ('mc_50', models.BigIntegerField(blank=True, db_column='MC_50', null=True)),
                ('mc_60', models.BigIntegerField(blank=True, db_column='MC_60', null=True)),
                ('mc_70', models.BigIntegerField(blank=True, db_column='MC_70', null=True)),
                ('mc_80', models.BigIntegerField(blank=True, db_column='MC_80', null=True)),
                ('mc_90', models.BigIntegerField(blank=True, db_column='MC_90', null=True)),
                ('mc_100', models.BigIntegerField(blank=True, db_column='MC_100', null=True)),
                ('over_100', models.BigIntegerField(blank=True, db_column='Over_100', null=True)),
            ],
            options={
                'verbose_name': '기본 요금대',
                'verbose_name_plural': '기본 요금대',
                'db_table': 'tb_contract_monthc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbContractTim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tim_3', models.BigIntegerField(blank=True, db_column='TiM_3', null=True)),
                ('tim_6', models.BigIntegerField(blank=True, db_column='TiM_6', null=True)),
                ('tim_12', models.BigIntegerField(blank=True, db_column='TiM_12', null=True)),
                ('tim_24', models.BigIntegerField(blank=True, db_column='TiM_24', null=True)),
                ('tim_36', models.BigIntegerField(blank=True, db_column='TiM_36', null=True)),
                ('tim_37', models.BigIntegerField(blank=True, db_column='TiM_37', null=True)),
            ],
            options={
                'verbose_name': '계약 기간대',
                'verbose_name_plural': '계약 기간대',
                'db_table': 'tb_contract_tim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbServiceCp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_0', models.BigIntegerField(blank=True, db_column='CP_0', null=True)),
                ('cp_1', models.BigIntegerField(blank=True, db_column='CP_1', null=True)),
                ('cp_2', models.BigIntegerField(blank=True, db_column='CP_2', null=True)),
                ('cp_3', models.BigIntegerField(blank=True, db_column='CP_3', null=True)),
                ('cp_4', models.BigIntegerField(blank=True, db_column='CP_4', null=True)),
            ],
            options={
                'verbose_name': '결합 상품 수',
                'verbose_name_plural': '결합 상품 수',
                'db_table': 'tb_service_cp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now_add=True, db_column='Change_time', verbose_name='변경 시간')),
                ('tech_services', models.IntegerField(blank=True, db_column='Tech_services', null=True, verbose_name='기술 서비스')),
                ('streaming_services', models.IntegerField(blank=True, db_column='Streaming_services', null=True, verbose_name='부가 서비스')),
                ('combined_product', models.IntegerField(blank=True, db_column='Combined_Product', null=True, verbose_name='결합 상품 수')),
                ('number_of_dependents', models.IntegerField(blank=True, db_column='Number_of_Dependents', null=True, verbose_name='가족 결합 수')),
            ],
            options={
                'verbose_name': '서비스 수정 로그',
                'verbose_name_plural': '서비스 수정 로그',
                'db_table': 'tb_service_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbServiceNod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nod_0', models.BigIntegerField(blank=True, db_column='NoD_0', null=True)),
                ('nod_1', models.BigIntegerField(blank=True, db_column='NoD_1', null=True)),
                ('nod_2', models.BigIntegerField(blank=True, db_column='NoD_2', null=True)),
                ('nod_3', models.BigIntegerField(blank=True, db_column='NoD_3', null=True)),
                ('nod_4', models.BigIntegerField(blank=True, db_column='NoD_4', null=True)),
                ('nod_5', models.BigIntegerField(blank=True, db_column='NoD_5', null=True)),
            ],
            options={
                'verbose_name': '가족 결합 수',
                'verbose_name_plural': '가족 결합 수',
                'db_table': 'tb_service_nod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbServiceSts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts_0', models.BigIntegerField(blank=True, db_column='StS_0', null=True)),
                ('sts_1', models.BigIntegerField(blank=True, db_column='StS_1', null=True)),
                ('sts_2', models.BigIntegerField(blank=True, db_column='StS_2', null=True)),
            ],
            options={
                'verbose_name': '부가 서비스 수',
                'verbose_name_plural': '부가 서비스 수',
                'db_table': 'tb_service_sts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbServiceTs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_0', models.BigIntegerField(blank=True, db_column='TS_0', null=True)),
                ('ts_1', models.BigIntegerField(blank=True, db_column='TS_1', null=True)),
                ('ts_2', models.BigIntegerField(blank=True, db_column='TS_2', null=True)),
                ('ts_3', models.BigIntegerField(blank=True, db_column='TS_3', null=True)),
                ('ts_4', models.BigIntegerField(blank=True, db_column='TS_4', null=True)),
            ],
            options={
                'verbose_name': '기술 서비스 수',
                'verbose_name_plural': '기술 서비스 수',
                'db_table': 'tb_service_ts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('customer_id', models.CharField(db_column='Customer_ID', max_length=10, primary_key=True, serialize=False, verbose_name='고객 아이디')),
                ('age', models.IntegerField(db_column='Age', verbose_name='나이')),
                ('satisfaction_score', models.IntegerField(db_column='Satisfaction_Score', verbose_name='고객 관리 점수')),
                ('membership', models.CharField(blank=True, db_column='Membership', max_length=10, null=True, verbose_name='멤버쉽')),
                ('churn_value', models.IntegerField(blank=True, db_column='Churn_Value', null=True, verbose_name='해지 여부')),
                ('changed', models.IntegerField(blank=True, db_column='Changed', null=True, verbose_name='변경 여부')),
                ('churn_proba', models.IntegerField(blank=True, db_column='Churn_proba', null=True, verbose_name='해지 확률')),
                ('churn_proba_group', models.CharField(blank=True, db_column='Churn_proba_group', max_length=10, null=True, verbose_name='관리 그룹')),
            ],
            options={
                'verbose_name': '유저 테이블',
                'verbose_name_plural': '유저 테이블',
                'db_table': 'tb_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUserAgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_10', models.BigIntegerField(blank=True, db_column='Under_10', null=True)),
                ('age_10', models.BigIntegerField(blank=True, db_column='Age_10', null=True)),
                ('age_20', models.BigIntegerField(blank=True, db_column='Age_20', null=True)),
                ('age_30', models.BigIntegerField(blank=True, db_column='Age_30', null=True)),
                ('age_40', models.BigIntegerField(blank=True, db_column='Age_40', null=True)),
                ('age_50', models.BigIntegerField(blank=True, db_column='Age_50', null=True)),
                ('age_60', models.BigIntegerField(blank=True, db_column='Age_60', null=True)),
                ('age_70', models.BigIntegerField(blank=True, db_column='Age_70', null=True)),
                ('age_80', models.BigIntegerField(blank=True, db_column='Age_80', null=True)),
                ('age_90', models.BigIntegerField(blank=True, db_column='Age_90', null=True)),
            ],
            options={
                'verbose_name': '나이대',
                'verbose_name_plural': '나이대',
                'db_table': 'tb_user_age_range',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUserCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churned', models.BigIntegerField(blank=True, db_column='Churned', null=True)),
                ('stayed', models.BigIntegerField(blank=True, db_column='Stayed', null=True)),
            ],
            options={
                'verbose_name': '해지 카테고리',
                'verbose_name_plural': '해지 카테고리',
                'db_table': 'tb_user_cv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now_add=True, db_column='Change_time', verbose_name='변경 시간')),
                ('age', models.IntegerField(db_column='Age', verbose_name='나이')),
                ('satisfaction_score', models.IntegerField(db_column='Satisfaction_Score', verbose_name='고객 관리 점수')),
                ('churn_value', models.IntegerField(blank=True, db_column='Churn_Value', null=True, verbose_name='해지 여부')),
            ],
            options={
                'verbose_name': '유저 수정 로그',
                'verbose_name_plural': '유저 수정 로그',
                'db_table': 'tb_user_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUserSs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_0', models.BigIntegerField(blank=True, db_column='SS_0', null=True)),
                ('ss_1', models.BigIntegerField(blank=True, db_column='SS_1', null=True)),
                ('ss_2', models.BigIntegerField(blank=True, db_column='SS_2', null=True)),
                ('ss_3', models.BigIntegerField(blank=True, db_column='SS_3', null=True)),
                ('ss_4', models.BigIntegerField(blank=True, db_column='SS_4', null=True)),
                ('ss_5', models.BigIntegerField(blank=True, db_column='SS_5', null=True)),
            ],
            options={
                'verbose_name': '관리 점수',
                'verbose_name_plural': '관리 점수',
                'db_table': 'tb_user_ss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbContract',
            fields=[
                ('customer', models.OneToOneField(db_column='Customer_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Telco_defence.tbuser', verbose_name='고객 아이디')),
                ('contract', models.CharField(blank=True, db_column='Contract', max_length=20, null=True, verbose_name='계약 종류')),
                ('tenure_in_months', models.BigIntegerField(blank=True, db_column='Tenure_in_months', null=True, verbose_name='계약 개월 수')),
                ('monthly_charge', models.FloatField(blank=True, db_column='Monthly_Charge', null=True, verbose_name='기본 요금')),
                ('total_revenue', models.FloatField(blank=True, db_column='Total_Revenue', null=True, verbose_name='총 요금')),
            ],
            options={
                'verbose_name': '요금제 정보',
                'verbose_name_plural': '요금제 정보',
                'db_table': 'tb_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbService',
            fields=[
                ('customer', models.OneToOneField(db_column='Customer_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Telco_defence.tbuser', verbose_name='고객 아이디')),
                ('tech_services', models.IntegerField(blank=True, db_column='Tech_services', null=True, verbose_name='기술 서비스')),
                ('streaming_services', models.IntegerField(blank=True, db_column='Streaming_services', null=True, verbose_name='부가 서비스')),
                ('combined_product', models.IntegerField(blank=True, db_column='Combined_Product', null=True, verbose_name='결합 상품 수')),
                ('number_of_dependents', models.IntegerField(blank=True, db_column='Number_of_Dependents', null=True, verbose_name='가족 결합 수')),
            ],
            options={
                'verbose_name': '서비스 정보',
                'verbose_name_plural': '서비스 정보',
                'db_table': 'tb_service',
                'managed': False,
            },
        ),
    ]
