# Generated by Django 4.2.6 on 2023-10-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telco_defence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbUserCltv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cltv_0', models.BigIntegerField(blank=True, null=True)),
                ('cltv_1', models.BigIntegerField(blank=True, null=True)),
                ('cltv_2', models.BigIntegerField(blank=True, null=True)),
                ('cltv_3', models.BigIntegerField(blank=True, null=True)),
                ('cltv_4', models.BigIntegerField(blank=True, null=True)),
                ('cltv_5', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '고객 점수',
                'verbose_name_plural': '고객 점수',
                'db_table': 'tb_user_cltv',
                'managed': False,
            },
        ),
    ]
